import pygame
pygame.init()
screen = pygame.display.set_mode()
screen.fill("red")
pygame.display.flip()
pygame.time.wait(2000)
pygame.draw.circle(screen, "blue", [500, 180], 50)
pygame.display.flip()
pygame.time.wait(2000)
pygame.draw.circle(screen, "blue", [500, 100], 40)
pygame.display.flip()
pygame.time.wait(2000)
pygame.draw.circle(screen, "blue", [500, 40], 30)
pygame.display.flip()
pygame.time.wait(2000)